# Generated by Django 3.1.1 on 2020-09-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=21)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=21)),
            ],
        ),
    ]
